# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
  branches:
    include:
      - main  # Replace with your target branch

variables:
  imageName: node-docker-sample
  tag: $(Build.BuildId)

stages:
  - stage: BuildAndPush
    displayName: Build and Push to ACR
    jobs:
      - job: Build
        displayName: Build and Push Docker Image
        pool:
          vmImage: 'ubuntu-latest'

        steps:
          - task: Checkout@1

          - task: Docker@2
            displayName: Build Docker image
            inputs:
              command: build
              repository: $(imageName)
              Dockerfile: '**/Dockerfile'
              tags: |
                $(tag)
                latest

          - task: Docker@2
            displayName: Push image to ACR
            inputs:
              command: push
              repository: $(imageName)
              tags: |
                $(tag)
                latest
              containerRegistry: '<AzureDevOpsACRServiceConnectionName>'
