# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
  branches:
    include:
      - main

variables:
  imageName: node-docker-sample
  tag: $(Build.BuildId)

stages:
  - stage: BuildAndPush
    displayName: Build and Push to ACR
    jobs:
      - job: Build
        displayName: Build and Push Docker Image
        pool:
          vmImage: 'ubuntu-latest'

        steps:
          - checkout: self
          - script: |
              echo "Listing files in the source directory:"
              ls -R $(Build.SourcesDirectory)
              displayName: 'List repo files'


          - task: Docker@2
            displayName: Build Docker image
            inputs:
              containerRegistry: 'ACR-SVC'
              repository: '$(imageName)'
              command: 'build'
              Dockerfile: src/Dockerfile
              buildContext: src
              tags: |
                $(tag)
                latest

          - task: Docker@2
            displayName: Push image to ACR
            inputs:
              containerRegistry: 'ACR-SVC'
              repository: '$(imageName)'
              command: 'push'
              tags: |
                $(tag)
                latest
