# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
  branches:
    include:
      - main

variables:
  imageName: node-docker-sample
  tag: $(Build.BuildId)

stages:
  - stage: BuildAndPush
    displayName: Build and Push to ACR
    jobs:
      - job: Build
        displayName: Build and Push Docker Image
        pool:
          vmImage: 'ubuntu-latest'

        steps:
          - checkout: self


          - task: Docker@2
            displayName: Build Docker image
            inputs:
              containerRegistry: 'ACR-SVC'
              repository: $(imageName)
              command: build
              Dockerfile: 'Dockerfile'
              buildContext: '$(Build.SourcesDirectory)'
              tags: |
                $(tag)
                latest

          - task: Docker@2
            displayName: Push image to ACR
            inputs:
              containerRegistry: 'ACR-SVC'
              repository: '$(imageName)'
              command: 'push'
              tags: |
                $(tag)
                latest
# CD pipeline
  - stage: Deploy
    displayName: Deploy to AKS
    jobs:
      - deployment: DeployApp
        displayName: Deploy to AKS Cluster
        environment: 'aks-dev'
        strategy:
          runOnce:
            deploy:
              steps:
                - task: Kubernetes@1
                  displayName: Set kubectl context
                  inputs:
                    connectionType: 'Azure Resource Manager'
                    azureSubscriptionEndpoint: 'Azure subscription 1(5e47e5a1-7dc4-4abb-87a2-f371200842ea)'
                    azureResourceGroup: 'rg-aks-demo'
                    kubernetesCluster: 'aks-demo'
                    namespace: 'default'
                    command: 'apply'
                    useConfigurationFile: true
                    configuration: '$(System.DefaultWorkingDirectory)/deployment.yaml'''
                    secretType: 'None'

