apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-sample
  labels:
    app: node-sample               # <-- Add this
spec:
  replicas: 1
  selector:
    matchLabels:
      app: node-sample
  template:
    metadata:
      labels:
        app: node-sample
    spec:
      containers:
        - name: node-sample
          image: containerregi.azurecr.io/node-docker-sample:latest
          ports:
            - containerPort: 3000
