trigger:
  branches:
    include:
      - main  # or your default branch

variables:
  imageName: node-docker-sample

stages:
  - stage: BuildAndPush
    displayName: Build and Push to ACR
    jobs:
      - job: Build
        pool:
          vmImage: 'ubuntu-latest'
        steps:
          - checkout: self

          - task: AzureCLI@2
            inputs:
              azureSubscription: '<Azure-Service-Connection-Name>'
              scriptType: bash
              scriptLocation: inlineScript
              inlineScript: |
                echo "Logging into ACR..."
                az acr login --name <your-acr-name>

                echo "Getting ACR login server..."
                ACR_LOGIN_SERVER=$(az acr show --name <your-acr-name> --query loginServer --output tsv)

                echo "Building Docker image..."
                docker build -t $ACR_LOGIN_SERVER/$(imageName):$(Build.BuildId) .

                echo "Pushing image to ACR..."
                docker push $ACR_LOGIN_SERVER/$(imageName):$(Build.BuildId)

                echo "##vso[task.setvariable variable=imageTag]$ACR_LOGIN_SERVER/$(imageName):$(Build.BuildId)"
